[package]
name = "roselib"
version = "0.1.0"
authors = ["Ralph Minderhoud <ralphminderhoud@gmail.com>"]
homepage = "ralphminderhoud.com"

[dependencies]
byteorder = "1.2"
failure = "0.1"
encoding_rs = "0.8"
serde = "1.0"
serde_derive = "1.0"
